<x-filament-panels::page>
<div class="kb-home">
 <div class="kb-welcome"><div><span class="kb-eyebrow">MAKE EVERY CONVERSATION COUNT</span><h2>A little closer to your audience.</h2><p>Welcome back, {{ explode(' ',auth()->user()->name)[0] }}. Here’s what’s happening with KemerBet.</p></div><a class="kb-button" href="{{ \App\Filament\Resources\Broadcasts\BroadcastResource::getUrl('create') }}">＋ New campaign</a></div>
 <div class="kb-metrics">
 @foreach([['Reachable audience',$subscribers,'People ready to hear from you','mint'],['New today',$kpis['new_today'],'New conversations, new possibilities','peach'],['Active this week',$kpis['active_7d'],'People who interacted in 7 days','lavender'],['Needs a reply',$openInbox,'Keep the conversation going','cream']] as [$label,$value,$hint,$color])
 <div class="kb-metric {{ $color }}"><span>{{ $label }}</span><strong>{{ number_format($value) }}</strong><small>{{ $hint }}</small></div>
 @endforeach
 </div>
 <div class="kb-main-grid"><section class="kb-card"><div class="kb-card-heading"><div><h3>Your audience is growing</h3><p>New members · last 14 days</p></div><span class="kb-pill">{{ array_sum($joins) }} joins</span></div>
 <div class="kb-chart" role="img" aria-label="Daily new audience members for the last fourteen days">
 @foreach($joins as $date=>$count)<div class="kb-chart-column"><span title="{{ $date }}: {{ $count }} joins" style="height:{{ max(3,($count/max(1,max($joins)))*150) }}px"></span><small>{{ \Carbon\Carbon::parse($date)->format('d') }}</small></div>@endforeach
 </div><div class="kb-chart-footer"><span>{{ \Carbon\Carbon::parse(array_key_first($joins))->format('d M') }}</span><span>{{ now()->timezone(config('app.display_timezone'))->format('d M') }}</span></div>
 </section><section class="kb-card kb-next"><span class="kb-eyebrow">A GOOD NEXT STEP</span><div class="kb-illustration" aria-hidden="true"><span>✦</span><div>↗</div><i>♡</i></div><h3>Something worth sharing?</h3><p>A useful update, a match reminder, or a friendly hello. Turn it into a conversation.</p><a class="kb-button kb-light" href="{{ \App\Filament\Resources\Broadcasts\BroadcastResource::getUrl('create') }}">Create a campaign →</a><small>Your audience’s preferences are always respected.</small></section></div>
 <div class="kb-main-grid"><section class="kb-card"><div class="kb-card-heading"><div><h3>Recent campaigns</h3><p>Your latest messages, all in one place</p></div><a href="{{ \App\Filament\Resources\Broadcasts\BroadcastResource::getUrl() }}">View all →</a></div>
 @forelse($campaigns as $campaign)<div class="kb-list-row"><div class="kb-round-icon">↗</div><div class="kb-row-main"><strong>{{ $campaign->name ?: 'Campaign #'.$campaign->id }}</strong><small>{{ $campaign->created_at->timezone(config('app.display_timezone'))->format('d M · H:i') }} · {{ number_format($campaign->sent) }} sent</small></div><span class="kb-pill status-{{ $campaign->status->value }}">{{ ucfirst($campaign->status->value) }}</span></div>@empty<div class="kb-empty"><span>✉</span><h4>Your first campaign starts here</h4><p>Write a message, choose your audience, and pick a time.</p><a href="{{ \App\Filament\Resources\Broadcasts\BroadcastResource::getUrl('create') }}">Let’s create one →</a></div>@endforelse
 </section><section class="kb-card"><div class="kb-card-heading"><div><h3>Coming up</h3><p>Scheduled in Addis Ababa time</p></div><a href="{{ \App\Filament\Pages\Calendar::getUrl() }}">Calendar →</a></div>
 @forelse($scheduled as $campaign)<div class="kb-list-row"><div class="kb-date"><b>{{ $campaign->scheduled_at->timezone(config('app.display_timezone'))->format('d') }}</b><small>{{ $campaign->scheduled_at->timezone(config('app.display_timezone'))->format('M') }}</small></div><div class="kb-row-main"><strong>{{ $campaign->name ?: 'Campaign #'.$campaign->id }}</strong><small>{{ $campaign->scheduled_at->timezone(config('app.display_timezone'))->format('H:i') }} · {{ $campaign->recurrence ? 'Repeating' : 'One-time' }}</small></div></div>@empty<div class="kb-empty kb-small"><span>☀</span><h4>A little breathing room</h4><p>No upcoming campaigns. Schedule one whenever you’re ready.</p></div>@endforelse
 <div class="kb-workspace-status"><span class="kb-status-dot"></span><div><strong>{{ $activeJourneys }} active journeys</strong><small>{{ $pendingUpdates }} incoming updates waiting</small></div><a href="{{ \App\Filament\Pages\DeliveryCenter::getUrl() }}">Delivery center →</a></div>
 </section></div>
</div></x-filament-panels::page>
